# Generated by Django 5.2.1 on 2025-05-09 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
